/** @format */

export const ACCOUNT_COPY = {
  title: 'Mi cuenta',
  sections: {
    overview: 'Mi cuenta',
    profile: 'Mi perfil',
    contributions: 'Mis contribuciones',
    session: 'Sesión actual',
  },
  overview: {
    intro:
      'Gestiona tu identidad, tu perfil público, tus contribuciones y el estado de tu sesión actual.',
    identityTitle: 'Identidad',
    profileTitle: 'Perfil',
    pointsTitle: 'Mis puntos',
    sessionTitle: 'Sesión actual',
    contributionsTitle: 'Mis contribuciones',
    noProfile: 'Todavía no has creado tu perfil.',
    createProfileCta: 'Crear perfil',
    editProfileCta: 'Editar perfil',
    contributionsCta: 'Ver contribuciones',
    sessionCta: 'Ver sesión actual',
  },
  labels: {
    userId: 'User ID',
    username: 'Username',
    email: 'Email',
    platformRole: 'Rol de plataforma',
    status: 'Estado',
    sessionId: 'Session ID',
    issuedAt: 'Emitido el',
    expiresAt: 'Expira el',
    displayName: 'Nombre visible',
    bio: 'Biografía',
    avatarUrl: 'Avatar URL',
    visibility: 'Visibilidad',
    createdAt: 'Creado el',
    updatedAt: 'Actualizado el',
    deviceId: 'Device ID',
    lastSeenAt: 'Última actividad',
    refreshTokenExpiresAt: 'Refresh expira el',
    contributionType: 'Tipo',
    targetEntityType: 'Entidad',
    targetEntityId: 'ID entidad',
    assetId: 'Asset ID',
    reviewStatus: 'Estado',
    reviewedAt: 'Revisada el',
    totalPoints: 'Puntos totales',
  },
  profile: {
    title: 'Mi perfil',
    subtitle:
      'Edita la información de tu perfil propio usando exactamente el contrato autenticado de /me/profile.',
    save: 'Guardar perfil',
    saving: 'Guardando...',
    success: 'Perfil guardado.',
    invalidForm: 'El formulario del perfil no es válido.',
    invalidVisibility: 'La visibilidad del perfil no es válida.',
    saveError: 'No se pudo guardar el perfil.',
    createMode: 'Todavía no has creado tu perfil.',
    visibilityOptions: {
      public: 'Público',
      private: 'Privado',
    },
  },
  contributions: {
    title: 'Mis contribuciones',
    subtitle:
      'Consulta tus contribuciones autenticadas con filtros, paginación y estados devueltos por el backend.',
    sort: 'Orden',
    reviewStatus: 'Estado de revisión',
    targetEntityType: 'Tipo de destino',
    allReviewStatuses: 'Todos los estados',
    allTargets: 'Todos los destinos',
    sortOptions: {
      created_at_desc: 'Creada ↓',
      created_at_asc: 'Creada ↑',
      updated_at_desc: 'Actualizada ↓',
      updated_at_asc: 'Actualizada ↑',
    },
    reviewStatusLabels: {
      pending: 'Pendiente',
      approved: 'Aprobada',
      rejected: 'Rechazada',
    },
    targetEntityTypeLabels: {
      stadium: 'Estadio',
      person: 'Persona',
    },
    paginationLabel: 'Página {current} de {total}',
    emptyFiltered: 'No hay resultados con los filtros actuales.',
    emptyInitial: 'Todavía no has enviado contribuciones.',
    loadError: 'No se pudieron cargar tus contribuciones.',
    reset: 'Restablecer',
    retry: 'Reintentar',
  },
  points: {
    retry: 'Reintentar',
    loadError: 'No se pudieron cargar tus puntos.',
  },
  session: {
    retry: 'Reintentar',
    loadError: 'No se pudo cargar la sesión actual.',
  },
} as const;
