/** @format */

const API_ROUTES = {
  ORGANIZATION_PARTICIPANTS: '/organization/participants',
  CAMPAIGNS: '/campaigns',
  GROUPS: '/groups',
  GROUP_BY_ID: (id: string) => `/groups/${id}`,
  GROUP_MEMBERS: (id: string) => `/groups/${id}/members`,
  CLUB_BY_SLUG: (slug: string) => `/clubs/${slug}`,
  CLUBS_ADMIN: '/admin/clubs',
  CLUB_ADMIN_BY_ID: (id: string) => `/admin/clubs/${id}`,
  STADIUMS_ADMIN: '/admin/stadiums',
  STADIUM_ADMIN_BY_ID: (id: string) => `/admin/stadiums/${id}`,
  ADMIN_COUNTRY_STADIUMS_CATALOG: (countryId: string) =>
    `/admin/countries/${countryId}/stadiums/catalog`,
  FEDERATIONS: '/federations',
  FEDERATION_BY_SLUG: (slug: string) => `/federations/${slug}`,
  FEDERATIONS_ADMIN: '/admin/federations',
  FEDERATION_ADMIN_BY_ID: (id: string) => `/admin/federations/${id}`,
  COUNTRIES: '/countries',
  COUNTRIES_ALL: '/countries/all',
  COUNTRY_BY_ID: (id: string) => `/countries/${id}`,
  COUNTRIES_ADMIN: '/admin/countries',
  ADMIN_COUNTRIES_ALL: '/admin/countries/all',
  COUNTRIES_ADMIN_ALL: '/admin/countries/all',
  COUNTRY_ADMIN_BY_ID: (id: string) => `/admin/countries/${id}`,
  COUNTRY_ADMIN_ACTIVATION: (id: string) => `/admin/countries/${id}/activation`,
  ADMIN_COUNTRY_PROVINCES: (countryId: string) =>
    `/admin/countries/${countryId}/provinces`,
  CITIES: '/cities',
  CITY_BY_ID: (id: string) => `/cities/${id}`,
  CITIES_ADMIN: '/admin/cities',
  CITY_ADMIN_BY_ID: (id: string) => `/admin/cities/${id}`,
  CITY_ADMIN_ACTIVATION: (id: string) => `/admin/cities/${id}/activation`,
  ADMIN_COUNTRY_CITIES: (countryId: string) =>
    `/admin/countries/${countryId}/cities`,
  CITIES_ADMIN_BY_COUNTRY: (countryId: string) =>
    `/admin/countries/${countryId}/cities`,
  CITIES_PUBLIC_BY_COUNTRY: (countryId: string) =>
    `/countries/${countryId}/cities`,
  EVENTS: '/events',
  EVENT_BY_ID: (id: string) => `/events/${id}`,
  EVENT_PARTICIPANTS: (id: string) => `/events/${id}/participants`,
  PLACES: '/places',
  PLACES_SEARCH: '/places/search',
  PLACE_BY_ID: (id: string) => `/places/${id}`,
  PLACES_BY_CITY: (cityId: string) => `/places/city/${cityId}`,
  FEATURE_FLAGS: '/feature-flags',
  FEATURE_FLAGS_ADMIN: '/admin/feature-flags/',
  FEATURE_FLAG_ADMIN_BY_ID: (id: string) => `/admin/feature-flags/${id}`,
  LEGAL: '/legal',
  LEGAL_BY_ID: (id: string) => `/legal/${id}`,
  LEGAL_TRANSLATION_BY_ID: (documentId: string, translationId: string) =>
    `/legal/${documentId}/translations/${translationId}`,
  LEGAL_TERMS: '/legal/terms',
  LEGAL_PRIVACY: '/legal/privacy',
  LEGAL_SUBSCRIPTION: '/legal/subscription',
  SPORTS: '/sports',
  SPORTS_ADMIN: '/sports/admin',
  SPORT_BY_ID: (id: string) => `/sports/${id}`,
  SPORT_ADMIN_BY_ID: (id: string) => `/sports/admin/${id}`,
  TEMPLATES: '/templates',
  QUIZZES: '/organization/exams',
  QUIZ_BY_UUID: (uuid: string) => `/exams/${uuid}`,
  EXPERTISE_BY_UUID: (uuid: string) => `/organization/expertises/${uuid}`,
  ANSWERS_BY_QUIZ: (uuid: string) => `/exams/${uuid}/answers`,
  QUESTIONS: '/questions',
  INVITATIONS: '/invitations',
  EXPERTISES: '/expertises',
  ORGANIZATION: '/organization',
  ORGANIZATION_EMPLOYEES: `/organization/users`,
  ORGANIZATION_TEMPLATES: `/organization/templates`,
  ORGANIZATION_CAMPAIGNS: `/organization/campaigns`,
  ORGANIZATION_INVITATIONS: `/organization/invitations`,
  ORGANIZATION_QUESTIONS: `/organization/questions`,
  ORGANIZATION_EXPERTISES: `/organization/expertises`,
  ORGANIZATION_BY_UUID: (uuid: string) => `/organizations/${uuid}`,
  AVAILABLE_QUESTIONS_COUNT: `/organization/questions/available-count`,
  ORGANIZATION_TEMPLATE_BY_UUID: (uuid: string) =>
    `/organization/templates/${uuid}`,
  ORGANIZATION_CAMPAIGN_BY_UUID: (uuid: string) =>
    `/organization/campaigns/${uuid}`,
  ORGANIZATION_QUIZZES_BY_UUID: (uuid: string) => `/organization/exams/${uuid}`,
  ORGANIZATION_QUESTION_BY_UUID: (uuid: string) =>
    `/organization/questions/${uuid}`,
  CAMPAIGN_PARTIPANTS: (uuid: string) =>
    `/organization/campaigns/${uuid}/participants`,
  CAMPAIGN_BY_UUID: (uuid: string) => `/campaigns/${uuid}`,
  CAMPAIGN_QUIZZES: (uuid: string) => `/organization/campaigns/${uuid}/exams`,
  AUTH_LOGIN: '/auth/login',
  AUTH_LOGIN_VERIFY_OTP: '/auth/login/verify-otp',
  AUTH_REGISTER: '/auth/registrations',
  AUTH_REGISTER_VERIFY_OTP: '/auth/registrations/verify-otp',
  AUTH_REFRESH: '/auth/sessions/refresh',
  AUTH_REVOKE: '/auth/sessions/revoke',
  SESSIONS_CURRENT: '/sessions/current',
  USERS: '/users',
  USER_BY_UUID: (uuid: string) => `/users/${uuid}`,
  USER_EMAIL: (uuid: string) => `/users/${uuid}/email`,
  USER_EMAIL_VERIFY: (uuid: string) => `/users/${uuid}/email/verify`,
  USER_BY_USERNAME: '/users/username',
  ME: '/me',
  ME_PROFILE: '/me/profile',
  MY_PARTICIPATIONS: '/me/participations',
} as const;

export default API_ROUTES;
