/** @format */

const SECTIONS = {
  ACCOUNT: 'Account',
  ACTIVITIES: 'Activities',
  ADD_GROUP: 'Create Group',
  ADD_PLACE: 'Create Place',
  ADD_PERSON: 'Create Person',
  ADD_CLUB: 'Create Club',
  ADD_COMPETITION: 'Create Competition',
  ADD_COMPETITION_EDITION: 'Create Competition Edition',
  ADD_COMPETITION_TYPE: 'Create Competition Type',
  ADD_BRAND: 'Create Brand',
  ADD_FEDERATION: 'Create Federation',
  ADD_CITY: 'Create City',
  ADD_STADIUM: 'Create Stadium',
  ADD_SEASON: 'Create Season',
  ADD_COUNTRY: 'Add Country',
  ADD_EVENT: 'Create Event',
  ADD_SPORT: 'Add Sport',
  ADD_USER: 'Add User',
  MEDIA: 'Media',
  AVATAR: 'Avatar',
  CITIES: 'Cities',
  INFORMATION: 'Information',
  COUNTRIES: 'Countries',
  DASHBOARD: 'Dashboard',
  EMAIL_PHONE: 'Email & Phone',
  EVENTS: 'Events',
  FLAGS: 'Flags',
  GROUPS: 'Groups',
  LEGAL: 'Legal',
  LOGOUT: 'Logout',
  MEMBERS: 'Members',
  NOTIFICATIONS: 'Notifications',
  PASSWORD: 'Manage Password', // NOSONAR
  PERMISSIONS: 'Manage Permissions',
  PLACES: 'Places',
  PREFERENCES: 'Preferences',
  PRIVACY: 'Privacy',
  PROFILE: 'Profile',
  SKILLS: 'Skills',
  SESSIONS: 'Sessions',
  SPORTS: 'Sports',
  CLUBS: 'Clubs',
  COMPETITIONS: 'Competitions',
  BRANDS: 'Brands',
  FEDERATIONS: 'Federations',
  PERSONS: 'Persons',
  STADIUMS: 'Stadiums',
  USERNAME: 'Username',
  USERS: 'Users',
} as const;

export default SECTIONS;
