/** @format */

const ONE_MINUTE = 60 * 1000;
const FIVE_MINUTES = 5 * ONE_MINUTE;
const TEN_MINUTES = 10 * ONE_MINUTE;
const FIFTEEN_MINUTES = 15 * ONE_MINUTE;
const THIRTY_MINUTES = 30 * ONE_MINUTE;
const ONE_HOUR = 60 * ONE_MINUTE;
const TWO_HOURS = 2 * ONE_HOUR;
const THREE_HOURS = 3 * ONE_HOUR;
const FOUR_HOURS = 4 * ONE_HOUR;
const FIVE_HOURS = 5 * ONE_HOUR;
const CURRENT_TIME = new Date().getTime();

export {
  CURRENT_TIME,
  ONE_MINUTE,
  FIVE_MINUTES,
  TEN_MINUTES,
  FIFTEEN_MINUTES,
  THIRTY_MINUTES,
  ONE_HOUR,
  TWO_HOURS,
  THREE_HOURS,
  FOUR_HOURS,
  FIVE_HOURS,
};
